[package]
name = "euler"
version = "0.1.0"
authors = ["David Harvey-Macaulay <alteous@outlook.com>"]

[dependencies]
approx = "0.1.1"
cgmath = "0.15"
mint = "0.4.2"

[features]
default = ["mint-support"]
mint-support = []